using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace BaseExpedition {
  public sealed class GameBootstrap : MonoBehaviour {
    PlayerState player; readonly BaseState baseState=new(); readonly ArmoryState armory=new();
    readonly List<EnemyState> enemies=new(), guardians=new(); readonly List<ProjectileState> projectiles=new(); readonly List<DropState> drops=new(); readonly List<FireWallState> fireWalls=new(); readonly List<DropState> lostLoot=new();
    readonly Dictionary<object,SpriteRenderer> views=new(); RegionId unlocked=RegionId.Forest; EnemyState boss; float spawnTimer, messageTimer; string message=""; bool victory; Vector2 touchMove; Camera cam;
    readonly string[] materials={"wood","stone","metal","magicShard","forestCore","mountainCore","mineCore"};

    void Awake() { Application.targetFrameRate=60; SetupCamera(); player=new PlayerState(); CreateTerrain(); SpawnGuardians(RegionId.Forest); SetMessage("從營火出發，探索森林並擊敗守衛。",4); }
    void SetupCamera() { cam=Camera.main; if(cam==null){var c=new GameObject("Main Camera");cam=c.AddComponent<Camera>();c.tag="MainCamera";} cam.orthographic=true;cam.orthographicSize=520;cam.transform.position=new Vector3(0,0,-10);cam.backgroundColor=new Color(.06f,.08f,.09f); }
    void CreateTerrain() { MakeRing("荒地",Definitions.WorldRadius,new Color(.45f,.42f,.34f),-5); MakeRing("礦場",Definitions.RadiusFor(RegionId.Mine),new Color(.18f,.20f,.22f),-4); MakeRing("山脈",Definitions.RadiusFor(RegionId.Mountain),new Color(.38f,.35f,.30f),-3); MakeRing("森林",Definitions.RadiusFor(RegionId.Forest),new Color(.15f,.34f,.20f),-2); MakeRing("基地",Definitions.BaseRadius,new Color(.12f,.25f,.18f),-1); }
    void MakeRing(string label,float radius,Color color,int order) { var go=new GameObject(label);go.transform.localScale=Vector3.one*radius*2;var sr=go.AddComponent<SpriteRenderer>();sr.sprite=RuntimeSprites.Circle;sr.color=color;sr.sortingOrder=order; }
    void Update() { if(victory){UpdateViews();return;} float dt=Time.deltaTime; ReadInput(dt); UpdatePlayer(dt); UpdateSpawning(dt); UpdateEnemies(dt); UpdateProjectiles(dt); UpdateFireWalls(dt); CollectDrops(); UpdateViews(); cam.transform.position=Vector3.Lerp(cam.transform.position,new Vector3(player.Position.x,player.Position.y,-10),1-Mathf.Exp(-8*dt)); if(messageTimer>0)messageTimer-=dt; }
    void ReadInput(float dt) {
      Vector2 move=new(Input.GetAxisRaw("Horizontal"),Input.GetAxisRaw("Vertical")); if(move.sqrMagnitude<.01f)move=touchMove; if(move.sqrMagnitude>1)move.Normalize();
      if(move.sqrMagnitude>.01f)player.Direction=move; player.Position += move*(player.IsDashing?720:280*player.MoveMultiplier)*dt;
      if((Input.GetKeyDown(KeyCode.LeftShift)||Input.GetKeyDown(KeyCode.RightShift)) && move.sqrMagnitude>.01f && player.DashCooldown<=0){player.DashRemaining=.18f;player.DashCooldown=1.2f;}
      if(Input.GetKeyDown(KeyCode.F))Interact(); if(Input.GetKeyDown(KeyCode.B)) baseState.Deposit(player.Inventory); if(Input.GetKeyDown(KeyCode.Alpha1))Equip(WeaponId.Torch); if(Input.GetKeyDown(KeyCode.Alpha2))Equip(WeaponId.Slingshot); if(Input.GetKeyDown(KeyCode.Alpha3))Equip(WeaponId.Spear); if(Input.GetKeyDown(KeyCode.Alpha4))Equip(WeaponId.Bow);
    }
    void UpdatePlayer(float dt) { player.DashRemaining=Mathf.Max(0,player.DashRemaining-dt);player.DashCooldown=Mathf.Max(0,player.DashCooldown-dt);player.AttackCooldown=Mathf.Max(0,player.AttackCooldown-dt); float limit=Definitions.RadiusFor(unlocked)-30; if(player.Position.magnitude>limit)player.Position=player.Position.normalized*limit; if(player.Position.magnitude<=Definitions.BaseRadius){player.Health=Mathf.Min(player.MaxHealth,player.Health+baseState.HealingLevel*dt);baseState.Deposit(player.Inventory);} TryAttack(); if(player.Health<=0)Respawn(); }
    void UpdateSpawning(float dt) { var region=Definitions.RegionAt(player.Position); if(region is RegionId.Base or RegionId.Wasteland)return; spawnTimer-=dt; int desired=region==RegionId.Forest?16:region==RegionId.Mountain?20:24; if(spawnTimer>0 || enemies.Count(e=>e.Definition.Region==region)<desired)return; spawnTimer=.63f; float angle=UnityEngine.Random.value*Mathf.PI*2; float dist=700+UnityEngine.Random.value*240; var p=player.Position+new Vector2(Mathf.Cos(angle),Mathf.Sin(angle))*dist; if(Definitions.RegionAt(p)!=region)return; var kinds=region==RegionId.Forest?new[]{EnemyKind.TreeSprite,EnemyKind.Seedling}:region==RegionId.Mountain?new[]{EnemyKind.StoneGolem,EnemyKind.RockThrower}:new[]{EnemyKind.IronBrute,EnemyKind.OreShooter}; enemies.Add(new EnemyState(kinds[UnityEngine.Random.Range(0,kinds.Length)],p)); }
    void UpdateEnemies(float dt) { foreach(var enemy in enemies.Concat(guardians).Append(boss).Where(e=>e!=null&&e.Alive).ToArray()) { enemy.AttackCooldown=Mathf.Max(0,enemy.AttackCooldown-dt);enemy.ChargeCooldown=Mathf.Max(0,enemy.ChargeCooldown-dt); Vector2 delta=player.Position-enemy.Position;float distance=delta.magnitude; bool inCorrectRegion=enemy.Definition.Guardian||enemy.Definition.Region==Definitions.RegionAt(player.Position)||enemy==boss; if(!inCorrectRegion||player.Position.magnitude<=Definitions.BaseRadius)continue; if(enemy==boss)UpdateBoss(enemy,dt,delta,distance); else { bool charging=enemy.Definition.Charger && distance<320 && distance>enemy.Definition.ContactRange && enemy.ChargeCooldown<=0; if(charging){enemy.ChargeRemaining=.42f;enemy.ChargeCooldown=3.2f;} float speed=enemy.Definition.Speed*(enemy.ChargeRemaining>0?3.4f:1);enemy.ChargeRemaining=Mathf.Max(0,enemy.ChargeRemaining-dt);if(distance>enemy.Definition.ContactRange)enemy.Position+=delta.normalized*speed*dt; if(distance<=enemy.Definition.ContactRange && enemy.AttackCooldown<=0){enemy.AttackCooldown=enemy.Definition.Cooldown;player.TakeDamage(enemy.Definition.Damage);} if(enemy.Definition.Ranged&&distance<=enemy.Definition.ContactRange&&enemy.AttackCooldown<=0){ } else if(enemy.Definition.Ranged&&distance<=enemy.Definition.ContactRange && enemy.AttackCooldown>enemy.Definition.Cooldown-.05f)FireEnemyProjectile(enemy); } }
      HandleDeaths(); }
    void UpdateBoss(EnemyState e,float dt,Vector2 delta,float distance) { if(e.AttackCooldown>0){if(distance>135)e.Position+=delta.normalized*e.Definition.Speed*dt;return;} e.AttackCooldown=2.5f; int action=UnityEngine.Random.Range(0,3); if(action==0 && distance<150)player.TakeDamage(35); else if(action==1){e.Position+=delta.normalized*240; if((e.Position-player.Position).magnitude<60)player.TakeDamage(42);} else for(int i=-3;i<=3;i++){var p=new ProjectileState(e.Position,Quaternion.Euler(0,0,i*15)*delta.normalized,300,360,22,false){Source=e};projectiles.Add(p);} }
    void FireEnemyProjectile(EnemyState e) { projectiles.Add(new ProjectileState(e.Position,(player.Position-e.Position).normalized,e.Definition.Region==RegionId.Mine?350:270,e.Definition.Region==RegionId.Mountain?300:250,e.Definition.Damage,false){Source=e}); }
    void TryAttack() { if(player.AttackCooldown>0||player.Position.magnitude<=Definitions.BaseRadius)return; var targets=enemies.Concat(guardians).Append(boss).Where(e=>e!=null&&e.Alive).OrderBy(e=>(e.Position-player.Position).sqrMagnitude).ToList();var target=targets.FirstOrDefault(e=>Vector2.Distance(e.Position,player.Position)<=260);if(target==null||Vector2.Distance(target.Position,player.Position)>player.Range+target.Definition.Radius)return;player.AttackCooldown=player.Cooldown;Vector2 direction=(target.Position-player.Position).normalized;if(player.Definition.Ranged){int shots=player.Modules.Contains("multishot")?3:1;for(int i=0;i<shots;i++){float angle=(i-(shots-1)/2)*.24f;var d=(Vector2)(Quaternion.Euler(0,0,angle)*direction);projectiles.Add(new ProjectileState(player.Position,d,player.Definition.ProjectileSpeed,player.Range,player.Damage,true){Piercing=player.Modules.Contains("piercing"),Homing=player.Modules.Contains("mountainHoming")});}}else {float effective=player.Range*(player.Modules.Contains("forestVortex")?.78f:1);foreach(var e in targets.Where(e=>InMelee(e,direction,effective)))e.Damage(player.Damage);if(player.Modules.Contains("fireStrike"))fireWalls.Add(new FireWallState{Origin=player.Position,Angle=Mathf.Atan2(direction.y,direction.x),Arc=player.Modules.Contains("forestVortex")?Mathf.PI*2:player.Definition.Arc*Mathf.Deg2Rad,Radius=effective*.72f,Damage=player.Damage});} }
    bool InMelee(EnemyState e,Vector2 direction,float range) {Vector2 d=e.Position-player.Position;if(d.magnitude>range+e.Definition.Radius)return false;if(player.Modules.Contains("forestVortex"))return true;if(player.Definition.Line){float forward=Vector2.Dot(d,direction);return forward>=0&&Mathf.Abs(Vector2.Perpendicular(direction).x*d.x+Vector2.Perpendicular(direction).y*d.y)<=player.Definition.ThrustWidth+e.Definition.Radius;}return Vector2.Angle(direction,d)<=player.Definition.Arc*.5f;}
    void UpdateProjectiles(float dt) { foreach(var p in projectiles.ToArray()){p.Remaining-=p.Speed*dt;if(p.Homing&&p.FromPlayer){var next=enemies.Concat(guardians).Append(boss).Where(e=>e!=null&&e.Alive).OrderBy(e=>(e.Position-p.Position).sqrMagnitude).FirstOrDefault();if(next!=null)p.Direction=Vector2.Lerp(p.Direction,(next.Position-p.Position).normalized,5*dt).normalized;}p.Position+=p.Direction*p.Speed*dt; if(p.FromPlayer){foreach(var e in enemies.Concat(guardians).Append(boss).Where(e=>e!=null&&e.Alive).ToArray())if(Vector2.Distance(p.Position,e.Position)<p.Radius+e.Definition.Radius){e.Damage(p.Damage);if(!p.Piercing){p.Remaining=0;break;}}}else if(Vector2.Distance(p.Position,player.Position)<p.Radius+18){player.TakeDamage(p.Damage);p.Remaining=0;}} projectiles.RemoveAll(p=>p.Remaining<=0);}
    void UpdateFireWalls(float dt) { foreach(var wall in fireWalls.ToArray()){wall.Remaining-=dt;foreach(var e in enemies.Concat(guardians).Append(boss).Where(e=>e!=null&&e.Alive&&!wall.Hit.Contains(e.Id)))if(Vector2.Distance(e.Position,wall.Origin)<=wall.Radius+e.Definition.Radius){wall.Hit.Add(e.Id);e.Damage(wall.Damage);}} fireWalls.RemoveAll(w=>w.Remaining<=0); }
    void HandleDeaths(){foreach(var e in enemies.Concat(guardians).Append(boss).Where(e=>e!=null&&!e.Alive).ToArray()){if(e==boss){victory=true;SetMessage("試玩版結束！外圈守衛者已擊敗。",999);continue;} if(e.Definition.Guardian){guardians.Remove(e);UnlockAfterGuardian(e);Drop(e,2,3);continue;} enemies.Remove(e);Drop(e,1,2);} }
    void Drop(EnemyState e,int min,int max){int count=UnityEngine.Random.Range(min,max+1);drops.Add(new DropState(e.Position,new ItemStack(e.Definition.Material,e.Definition.MaterialLabel,count)));float chance=e.Definition.Region==RegionId.Forest?.3f:e.Definition.Region==RegionId.Mountain?.5f:.8f;if(UnityEngine.Random.value<chance)drops.Add(new DropState(e.Position+UnityEngine.Random.insideUnitCircle*16,new ItemStack("magicShard","魔法碎片",1)));}
    void UnlockAfterGuardian(EnemyState e){if(e.Definition.Region!=unlocked)return;unlocked=unlocked switch{RegionId.Forest=>RegionId.Mountain,RegionId.Mountain=>RegionId.Mine,RegionId.Mine=>RegionId.Wasteland,_=>unlocked};if(unlocked==RegionId.Wasteland){boss=new EnemyState(EnemyKind.OuterBoss,Vector2.right*(Definitions.RadiusFor(RegionId.Mine)+Definitions.WastelandWidth*.5f));SetMessage("外圈守衛者現身，前往荒地！",5);}else{SpawnGuardians(unlocked);SetMessage($"{RegionName(unlocked)}已解鎖！",4);}}
    void SpawnGuardians(RegionId region){EnemyKind kind=region==RegionId.Forest?EnemyKind.ForestGuardian:region==RegionId.Mountain?EnemyKind.MountainGuardian:EnemyKind.MineGuardian;float radius=Definitions.RadiusFor(region)-150;foreach(var d in new[]{Vector2.up,Vector2.right,Vector2.down,Vector2.left})guardians.Add(new EnemyState(kind,d*radius));}
    void CollectDrops(){foreach(var d in drops.ToArray())Collect(d,drops);foreach(var d in lostLoot.ToArray())Collect(d,lostLoot);}
    void Collect(DropState d,List<DropState> source){if(Vector2.Distance(player.Position,d.Position)>=34)return;int rest=player.Inventory.Add(d.Item);source.Remove(d);if(rest>0){d.Item.Quantity=rest;source.Add(d);SetMessage("背包已滿。",2);}}
    void Respawn(){foreach(var s in player.Inventory.TakeAll())lostLoot.Add(new DropState(player.Position,s));player.Position=Vector2.zero;player.Health=player.MaxHealth;player.DashRemaining=0;SetMessage("你倒下了。遺失物留在原地。",3);}
    void Equip(WeaponId id){if(armory.Owned.Contains(id)){player.Weapon=id;SetMessage($"裝備：{Definitions.Weapons[id].Label}",2);}}
    void CraftWeapon(WeaponId id) { if(!baseState.Built.Contains("workbench")){SetMessage("先建造工作台。",2);return;} if(armory.Craft(id,baseState,player.Inventory))SetMessage($"已製作 {Definitions.Weapons[id].Label}。",2);else SetMessage("素材不足或武器已持有。",2); }
    void UpgradeWeapon() { var cost=new Dictionary<string,int>{{player.Definition.UpgradeMaterial,(player.WeaponLevel+1)*10},{"magicShard",player.WeaponLevel==0?2:player.WeaponLevel==1?5:8}};if(player.WeaponLevel>=3){SetMessage("武器已滿級。",2);return;}if(baseState.Consume(cost,player.Inventory)){player.WeaponLevel++;SetMessage("武器已升級。",2);}else SetMessage("升級素材不足。",2); }
    void UpgradeArmor() { int next=Mathf.RoundToInt(player.Armor/3)+1;var mat=next==1?"wood":next==2?"stone":"metal";int amount=next==1?20:25;int shards=next==1?2:next==2?4:6;if(next>3){SetMessage("護甲已滿級。",2);return;}if(baseState.Consume(new Dictionary<string,int>{{mat,amount},{"magicShard",shards}},player.Inventory)){player.Armor=next==1?3:next==2?6:10;SetMessage("護甲已升級。",2);}else SetMessage("護甲素材不足。",2); }
    void UpgradeBoots() { int current=Mathf.RoundToInt((player.MoveMultiplier-1)*10);int next=current+1;var mat=next==1?"wood":next==2?"stone":"metal";int amount=next==1?15:20;int shards=next==1?2:next==2?4:6;if(next>3){SetMessage("靴子已滿級。",2);return;}if(baseState.Consume(new Dictionary<string,int>{{mat,amount},{"magicShard",shards}},player.Inventory)){player.MoveMultiplier=1+.1f*next;SetMessage("靴子已升級。",2);}else SetMessage("靴子素材不足。",2); }
    void UpgradeBackpack(){int next=player.Inventory.SlotCount==5?7:player.Inventory.SlotCount==7?9:11;string mat=next==7?"wood":next==9?"stone":"metal";int shards=next==7?2:next==9?4:6;if(player.Inventory.SlotCount>=11){SetMessage("背包已滿級。",2);return;}if(baseState.Consume(new Dictionary<string,int>{{mat,20},{"magicShard",shards}},player.Inventory)){player.Inventory.UpgradeSlots(next);SetMessage("背包容量已增加。",2);}else SetMessage("背包升級素材不足。",2);}
    void AddModule(string id,Dictionary<string,int> cost){if(!baseState.Built.Contains("enchantTable")){SetMessage("先建造注魔台。",2);return;}if(player.Modules.Contains(id)){SetMessage("模組已安裝。",2);return;}if(baseState.Consume(cost,player.Inventory)){player.Modules.Add(id);SetMessage("注魔完成。",2);}else SetMessage("注魔素材不足。",2);}
    void Interact(){if(player.Position.magnitude>170){SetMessage("靠近基地設施後按 F。",2);return;}if(!baseState.Warehouse){if(baseState.Consume(new Dictionary<string,int>{{"wood",20}},player.Inventory)){baseState.Built.Add("warehouse");SetMessage("已建造倉庫。資源會自動存放。",3);}else SetMessage("建造倉庫需要木材 ×20。",2);return;} if(!baseState.Built.Contains("workbench")){if(baseState.Consume(new Dictionary<string,int>{{"wood",30},{"magicShard",2}},player.Inventory)){baseState.Built.Add("workbench");SetMessage("已建造工作台。按 1–4 切換武器。",3);}else SetMessage("工作台需要木材 ×30、碎片 ×2。",2);return;} if(!baseState.Built.Contains("enchantTable")){if(baseState.Consume(new Dictionary<string,int>{{"wood",20},{"stone",25},{"magicShard",5}},player.Inventory)){baseState.Built.Add("enchantTable");SetMessage("已建造注魔台。",3);}else SetMessage("注魔台需要木材 ×20、石材 ×25、碎片 ×5。",2);return;}SetMessage("基地已完成；可繼續收集、升級與挑戰 Boss。",2);}
    string RegionName(RegionId id)=>id switch{RegionId.Forest=>"森林",RegionId.Mountain=>"山脈",RegionId.Mine=>"礦場",_=>"荒地"}; void SetMessage(string text,float duration){message=text;messageTimer=duration;}
    void UpdateViews(){var active=new HashSet<object>(); AddView(player,player.Position,new Color(.98f,.80f,.33f),30,10,active);foreach(var e in enemies.Concat(guardians).Append(boss).Where(e=>e!=null&&e.Alive)){Color c=e==boss?new Color(.8f,.18f,.15f):e.Definition.Region==RegionId.Forest?new Color(.38f,.72f,.31f):e.Definition.Region==RegionId.Mountain?new Color(.55f,.51f,.45f):new Color(.67f,.31f,.17f);AddView(e,e.Position,c,e.Definition.Radius*2,20,active);}foreach(var p in projectiles)AddView(p,p.Position,p.FromPlayer?Color.white:new Color(.95f,.35f,.2f),12,25,active);foreach(var d in drops)AddView(d,d.Position,Color.cyan,16,15,active);foreach(var d in lostLoot)AddView(d,d.Position,Color.magenta,22,15,active);foreach(var v in views.Where(p=>!active.Contains(p.Key)).ToArray()){Destroy(v.Value.gameObject);views.Remove(v.Key);}}
    void AddView(object key,Vector2 pos,Color color,float size,int order,HashSet<object> active){active.Add(key);if(!views.TryGetValue(key,out var sr)){var go=new GameObject("View");sr=go.AddComponent<SpriteRenderer>();sr.sprite=RuntimeSprites.Circle;views[key]=sr;}sr.transform.position=pos;sr.transform.localScale=Vector3.one*size;sr.color=color;sr.sortingOrder=order;}
    void OnGUI(){GUI.skin.label.fontSize=18;GUI.Box(new Rect(14,14,370,155),"基地探索");GUI.Label(new Rect(28,44,330,25),$"生命：{Mathf.CeilToInt(player.Health)} / {player.MaxHealth}    護甲：{player.Armor}");GUI.Label(new Rect(28,70,330,25),$"武器：{player.Definition.Label} Lv.{player.WeaponLevel}    區域：{RegionName(Definitions.RegionAt(player.Position))}");GUI.Label(new Rect(28,96,330,25),$"背包：{player.Inventory.UsedSlots}/{player.Inventory.SlotCount} 格    已解鎖：{RegionName(unlocked)}");GUI.Label(new Rect(28,122,330,25),"WASD 移動｜Shift 衝刺｜F 互動｜1–4 武器");if(messageTimer>0){GUI.Box(new Rect(Screen.width*.5f-250,20,500,45),message);}if(boss!=null&&boss.Alive){GUI.Box(new Rect(Screen.width*.5f-220,70,440,30),$"外圈守衛者  {Mathf.CeilToInt(boss.Health)} / {boss.Definition.MaxHealth}");}if(player.Position.magnitude<180)DrawBaseMenu();if(Application.isMobilePlatform){if(GUI.RepeatButton(new Rect(20,Screen.height-100,85,80),"←"))touchMove=Vector2.left;else if(GUI.RepeatButton(new Rect(115,Screen.height-100,85,80),"→"))touchMove=Vector2.right;else if(GUI.RepeatButton(new Rect(67,Screen.height-185,85,80),"↑"))touchMove=Vector2.up;else if(GUI.RepeatButton(new Rect(67,Screen.height-15,85,80),"↓"))touchMove=Vector2.down;else touchMove=Vector2.zero;if(GUI.Button(new Rect(Screen.width-125,Screen.height-100,105,70),"衝刺")){if(player.DashCooldown<=0){player.DashRemaining=.18f;player.DashCooldown=1.2f;}}if(GUI.Button(new Rect(Screen.width-125,Screen.height-185,105,70),"互動"))Interact();}}
    void DrawBaseMenu(){float x=Screen.width-260,y=14;GUI.Box(new Rect(x,y,245,330),"基地設施");if(GUI.Button(new Rect(x+10,y+32,108,28),"存入資源"))baseState.Deposit(player.Inventory);if(GUI.Button(new Rect(x+125,y+32,108,28),"升級背包"))UpgradeBackpack();if(GUI.Button(new Rect(x+10,y+68,108,28),"製作彈弓"))CraftWeapon(WeaponId.Slingshot);if(GUI.Button(new Rect(x+125,y+68,108,28),"製作長槍"))CraftWeapon(WeaponId.Spear);if(GUI.Button(new Rect(x+10,y+104,108,28),"製作弓箭"))CraftWeapon(WeaponId.Bow);if(GUI.Button(new Rect(x+125,y+104,108,28),"升級武器"))UpgradeWeapon();if(GUI.Button(new Rect(x+10,y+140,108,28),"升級護甲"))UpgradeArmor();if(GUI.Button(new Rect(x+125,y+140,108,28),"升級靴子"))UpgradeBoots();if(GUI.Button(new Rect(x+10,y+176,108,28),"火焰打擊"))AddModule("fireStrike",new Dictionary<string,int>{{"wood",5},{"magicShard",5}});if(GUI.Button(new Rect(x+125,y+176,108,28),"多重散射"))AddModule("multishot",new Dictionary<string,int>{{"stone",5},{"magicShard",5}});if(GUI.Button(new Rect(x+10,y+212,108,28),"衝擊波"))AddModule("shockwave",new Dictionary<string,int>{{"wood",5},{"magicShard",5}});if(GUI.Button(new Rect(x+125,y+212,108,28),"穿透"))AddModule("piercing",new Dictionary<string,int>{{"stone",5},{"magicShard",5}});GUI.Label(new Rect(x+10,y+252,225,70),"F：依序建造倉庫、工作台、注魔台\n模組依武器相容性自動作用。\n武器 1–4 切換。");}
  }
  static class RuntimeSprites { static Sprite circle; public static Sprite Circle {get {if(circle!=null)return circle;const int n=64;var tex=new Texture2D(n,n,TextureFormat.RGBA32,false);for(int y=0;y<n;y++)for(int x=0;x<n;x++){float dx=(x-(n-1)/2f)/(n/2f),dy=(y-(n-1)/2f)/(n/2f);tex.SetPixel(x,y,dx*dx+dy*dy<=1?Color.white:Color.clear);}tex.Apply();circle=Sprite.Create(tex,new Rect(0,0,n,n),new Vector2(.5f,.5f),n);return circle;}} }
}
